In [1]:
def calculate_carbon_footprint(energy_consumption, emission_factors):
    return energy_consumption * emission_factors
calculate_carbon_footprint(4,5)

20

In [2]:
energy_consumption = 1000
emission_factors = 0.475

carbon_footprint = calculate_carbon_footprint(energy_consumption,emission_factors)
print(f"carbon footprint: {carbon_footprint}kg CO2")

carbon footprint: 475.0kg CO2


In [3]:
cities = [
    {"name": "mysore","carbon_footprint":500},
    {"name": "chennai","carbon_footprint":350},
    {"name": "mangalore","carbon_footprint":600},
    {"name": "bangalore","carbon_footprint":200},
]

sustainabilty_threshold = 400
sustainabilty_cities = list(filter(lambda city: city["carbon_footprint"] < sustainabilty_threshold,cities))

print("sustainabilty_cities")
for city in sustainabilty_cities:
  print(f"{city['name']}: {city['carbon_footprint']}kg CO2")

sustainabilty_cities
chennai: 350kg CO2
bangalore: 200kg CO2


In [4]:
class Person:
    def __init__(self,name,age):
        self.name=name
        self.age=age

In [5]:
person = Person("John",30)
print(person.name)
print(person.age)

John
30


In [6]:
class car: #encapulation #public
  wheels = 4

  def __init__(self,make,year):
    self.make=make
    self.year=year

  def start_engine(self):
    print("engine started")

  @classmethod
  def get_wheels(cls):
    return cls.wheels

  @staticmethod
  def is_motor_vehicle():
    return True

In [7]:
car1 = car("Toyota",2022)
print(car1.make)
print(car1.year)
car1.start_engine()
print(car.get_wheels())
print(car.is_motor_vehicle())

Toyota
2022
engine started
4
True


In [8]:
class Person:#protected
  def __init__(self,name,age):
    self._name=name
    self._age=age

  def get_name(self):
    return self._name

In [9]:
person = Person("puuu",20)

In [10]:
person.get_name()

'puuu'

In [11]:
person._name

'puuu'

In [12]:
class Person:#private
  def __init__(self,name,age):
    self.__name=name
    self.__age=age

  def get_name(self):
    return self.__name

In [13]:
person = Person("niii",20)
person.get_name()

'niii'

In [14]:
#inheritance

class vehicle:
  def __init__(self,make,year):
    self.make=make
    self.year=year

  def display_info(self):
    print(f"make:{self.make},year:{self.year}")

class car(vehicle):
  def __init__(self,make,year,model):
    super().__init__(make,year)
    self.model=model

  def display_info(self):
    return f"{self.make} {self.model} {self.year}"




In [15]:
my_car = car("Toyota",2022,"Camry")
my_car.display_info()

'Toyota Camry 2022'

In [16]:
class Animal:
    def make_sound(self):
        print("Animal is making a sound")

class Dog(Animal):
    def make_sound(self):
        print("Dog is barking")


In [17]:
dog = Dog()
dog.make_sound()

Dog is barking


In [18]:
#overloading
class Example:
  def sum(self,*args):
    return sum(args)


In [19]:
obj = Example()
obj.sum(1,2,3,4)

10

In [20]:
import pandas as pd
x = pd.Series([1,2,3,4])
x

0    1
1    2
2    3
3    4
dtype: int64

In [21]:
import numpy as np
array_3d = np.array([
    [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]],

    [[13, 14, 15, 16],
     [17, 18, 19, 20],
     [21, 22, 23, 24]]
])

print("3D Array:")
print(array_3d)
print("\nShape of the 3D Array:")
print(array_3d.shape)

3D Array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

Shape of the 3D Array:
(2, 3, 4)


In [22]:
array_3d.ndim

3

In [23]:
import pandas as pd
renewable_sources = ['solar','wind','hydro','tidal']
rs = pd.Series(renewable_sources)
rs

0    solar
1     wind
2    hydro
3    tidal
dtype: object

In [24]:
#dataframe
data = {
    'project':['solar farm','wind turbine','hydro plant','tidal station'],
    'technology':['solar','wind','hydro','tidal'],
    'capacity(MW)':[1000,500,200,300],
    'cost($)':[100000,50000,20000,30000],
    'location':['india','china','usa','japan'],
    'yoc':[2020,2021,2022,2023]
}
df = pd.DataFrame(data)
df


project technology  capacity(MW)  cost($) location   yoc
0     solar farm      solar          1000   100000    india  2020
1   wind turbine       wind           500    50000    china  2021
2    hydro plant      hydro           200    20000      usa  2022
3  tidal station      tidal           300    30000    japan  2023

In [25]:
df.columns

Index(['project', 'technology', 'capacity(MW)', 'cost($)', 'location', 'yoc'], dtype='object')

In [26]:
df['project']

0       solar farm
1     wind turbine
2      hydro plant
3    tidal station
Name: project, dtype: object

In [27]:
df['yoc']

0    2020
1    2021
2    2022
3    2023
Name: yoc, dtype: int64

In [28]:
#filtering based on capacity
high_capacity = df[df['capacity(MW)']>200]
print(high_capacity)

         project technology  capacity(MW)  cost($) location   yoc
0     solar farm      solar          1000   100000    india  2020
1   wind turbine       wind           500    50000    china  2021
3  tidal station      tidal           300    30000    japan  2023


In [29]:
#cost per MW = cost/capacity
df['cost/MW'] = df['cost($)']/df['capacity(MW)']
df


project technology  capacity(MW)  cost($) location   yoc  cost/MW
0     solar farm      solar          1000   100000    india  2020    100.0
1   wind turbine       wind           500    50000    china  2021    100.0
2    hydro plant      hydro           200    20000      usa  2022    100.0
3  tidal station      tidal           300    30000    japan  2023    100.0

In [30]:
# aggregation
total_cost = df['cost($)'].sum()
total_capacity = df['capacity(MW)'].sum()
print(total_cost)
print(total_capacity)

200000
2000


In [31]:
#groupby
df.groupby('technology')['capacity(MW)'].sum()

technology
hydro     200
solar    1000
tidal     300
wind      500
Name: capacity(MW), dtype: int64

In [32]:
#numpy
import numpy as np#1D
a=np.array([1,2])
a

array([1, 2])

In [33]:
a.ndim

1

In [34]:
b=np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [35]:
b.ndim

2

In [36]:
c=np.array([[[1,2,3,4],[2,3,4,6],[2,3,4,6]]])
c

array([[[1, 2, 3, 4],
        [2, 3, 4, 6],
        [2, 3, 4, 6]]])

In [37]:
c.ndim

3

In [38]:
#random
z=np.random.rand(5)
z

array([0.60281095, 0.8110429 , 0.44349403, 0.04716708, 0.69522964])

In [39]:
y=np.random.rand(4,4)
y

array([[0.71248036, 0.19442897, 0.48990283, 0.73423155],
       [0.43053726, 0.85422385, 0.70387635, 0.85201253],
       [0.97773874, 0.47254286, 0.07989997, 0.32216616],
       [0.41383801, 0.55720174, 0.61751264, 0.33859193]])

In [40]:
x=np.random.randn(5)
x

array([-0.18028486,  0.16901554,  1.69341382, -1.94370234, -0.49093516])

In [41]:
p=np.random.randint(1,10,5)
p

array([9, 7, 1, 4, 7])

In [42]:
p=np.random.randint(1,10,size=(3,3))
p

array([[6, 9, 3],
       [9, 1, 7],
       [5, 3, 9]])

In [43]:
q=np.random.choice(10,4)
q

array([0, 0, 6, 5])

In [44]:
q=np.random.choice(5,5)
q

array([3, 0, 1, 3, 0])

In [45]:
q=np.random.choice(5,5,replace=False)
q

array([1, 3, 2, 4, 0])